syntax = "proto3";

package scheduler.client.v1;

option java_multiple_files = true;
option java_package = "com.scheduler.proto.client";

import "scheduler/v1/common.proto";

// Client -> Coordinator
message SubmitJobRequest {
  string name = 1;
  string artifact_uri = 2;
  reserved 3;
  map<string, string> params = 4;
  int32 priority = 5;
  repeated scheduler.v1.InputFile input_files = 6;
  reserved 7;
  scheduler.v1.ResourceRequirements resources = 8;
}

// Coordinator -> Client
message SubmitJobResponse {
  scheduler.v1.Job job = 1;
}

// Client -> Coordinator
message GetJobStatusRequest {
  string job_id = 1;
}

// Coordinator -> Client
message GetJobStatusResponse {
  scheduler.v1.Job job = 1;
}

// Client -> Coordinator
message ListJobFilesRequest {
  string job_id = 1;
}

// Coordinator -> Client
message ListJobFilesResponse {
  repeated FileInfo files = 1;
}

// Client -> Coordinator
message GetJobOutputRequest {
  string job_id = 1;
  string path = 2;
}

// Coordinator -> Client
message GetJobOutputResponse {
  oneof data {
    FileInfo header = 1;
    bytes chunk = 2;
  }
}

message FileInfo {
  string name = 1;
  int64 size_bytes = 2;
}

service ClientService {
  // Client -> Coordinator
  rpc SubmitJob(SubmitJobRequest) returns (SubmitJobResponse);
  // Client -> Coordinator
  rpc GetJobStatus(GetJobStatusRequest) returns (GetJobStatusResponse);
  // Client -> Coordinator
  rpc ListJobFiles(ListJobFilesRequest) returns (ListJobFilesResponse);
  // Client -> Coordinator
  rpc GetJobOutput(GetJobOutputRequest) returns (stream GetJobOutputResponse);
}
